language: java
jdk:
  - openjdk8

notifications:
  email:
    recipients:
      - jaychang1987@gmail.com

script:
  - travis_retry mvn -B clean
  - travis_retry mvn -B package jacoco:report coveralls:report

branches:
  only:
    - master