notifications:
  email:
    recipients:
      - jaychang1987@gmail.com

language: java

sudo: false
script:
  - travis_retry mvn -B clean
  - travis_retry mvn -B package jacoco:report coveralls:report